// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_RegistroDeportivo;

namespace api_RegistroDeportivo.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221101054821_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Alumno", b =>
                {
                    b.Property<int>("dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("distrito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("dni");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Matricula", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("alumnodni")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.HasIndex("alumnodni");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Matricula", b =>
                {
                    b.HasOne("api_RegistroDeportivo.Entitys.Alumno", "alumno")
                        .WithMany("matricula")
                        .HasForeignKey("alumnodni");

                    b.Navigation("alumno");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Alumno", b =>
                {
                    b.Navigation("matricula");
                });
#pragma warning restore 612, 618
        }
    }
}
