// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_RegistroDeportivo;

namespace api_RegistroDeportivo.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Alumno", b =>
                {
                    b.Property<int>("codAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("codEntrenador")
                        .HasColumnType("int");

                    b.Property<int>("codHorario")
                        .HasColumnType("int");

                    b.Property<int>("codLocal")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dni")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<int>("dniApo")
                        .HasColumnType("int");

                    b.Property<int?>("entrenadorcodEntrenador")
                        .HasColumnType("int");

                    b.Property<string>("fchNacimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("horarioscodHorario")
                        .HasColumnType("int");

                    b.Property<int?>("localescodLocal")
                        .HasColumnType("int");

                    b.Property<string>("nomapeApo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("telfApo")
                        .HasColumnType("int");

                    b.HasKey("codAlumno");

                    b.HasIndex("entrenadorcodEntrenador");

                    b.HasIndex("horarioscodHorario");

                    b.HasIndex("localescodLocal");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Entrenador", b =>
                {
                    b.Property<int>("codEntrenador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("codHorario")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<int?>("horarioscodHorario")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("codEntrenador");

                    b.HasIndex("horarioscodHorario");

                    b.ToTable("Entrenador");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Horarios", b =>
                {
                    b.Property<int>("codHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("codHorario");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Locales", b =>
                {
                    b.Property<int>("codLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codLocal");

                    b.ToTable("Locales");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Matricula", b =>
                {
                    b.Property<int>("codmatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("alumnocodAlumno")
                        .HasColumnType("int");

                    b.Property<int>("codAlumno")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codmatricula");

                    b.HasIndex("alumnocodAlumno");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Alumno", b =>
                {
                    b.HasOne("api_RegistroDeportivo.Entitys.Entrenador", "entrenador")
                        .WithMany("Alumnos")
                        .HasForeignKey("entrenadorcodEntrenador");

                    b.HasOne("api_RegistroDeportivo.Entitys.Horarios", "horarios")
                        .WithMany("Alumnos")
                        .HasForeignKey("horarioscodHorario");

                    b.HasOne("api_RegistroDeportivo.Entitys.Locales", "locales")
                        .WithMany("Alumnos")
                        .HasForeignKey("localescodLocal");

                    b.Navigation("entrenador");

                    b.Navigation("horarios");

                    b.Navigation("locales");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Entrenador", b =>
                {
                    b.HasOne("api_RegistroDeportivo.Entitys.Horarios", "horarios")
                        .WithMany("entrenador")
                        .HasForeignKey("horarioscodHorario");

                    b.Navigation("horarios");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Matricula", b =>
                {
                    b.HasOne("api_RegistroDeportivo.Entitys.Alumno", "alumno")
                        .WithMany("matricula")
                        .HasForeignKey("alumnocodAlumno");

                    b.Navigation("alumno");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Alumno", b =>
                {
                    b.Navigation("matricula");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Entrenador", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Horarios", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("entrenador");
                });

            modelBuilder.Entity("api_RegistroDeportivo.Entitys.Locales", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
